name = "rootrecord-license"
main = "src/index.ts"
compatibility_date = "2024-11-01"
account_id = "ec0a927534948eaade3c4ed6cad4172c"

[[d1_databases]]
binding = "DB"
database_name = "rootrecord_license"
database_id = "a25063b7-cf0f-460f-9bb4-d06f270a4e65"
